plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.airplanerefresh'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.airplanerefresh'

        minSdk 19
        targetSdk 28

        versionCode 2
        versionName "2.0"

        vectorDrawables {
            useSupportLibrary false
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false

            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'
            )
        }

        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}